src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @ORM\Table(name="posts")
 */
class Post
{
    /**
     * Post constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->slugify = new Slugify();
        $this->setIsModerated(false);
        $this->comments = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param mixed $username
     * @return Post
     */
    public function setUsername($username): self
    {
        $this->username = $username;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     * @return Post
     */
    public function setEmail($email): Post
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHomepage()
    {
        return $this->homepage;
    }

    /**
     * @param mixed $homepage
     * @return Post
     */
    public function setHomepage($homepage): self
    {
        $this->homepage = $homepage;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * @param mixed $text
     * @return Post
     */
    public function setText($text): Post
    {
        $this->text = $text;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return Post
     */
    public function setSlug($slug): Post
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @return string
     */
    public function getCreatedAtString(): string
    {
        return date("Y-m-d H:i:s", $this->created_at->getTimestamp());
    }

    /**
     * @param \DateTimeInterface $created_at
     * @return Post
     */
    public function setCreatedAt(\DateTimeInterface $created_at): Post
    {
        $this->created_at = $created_at;
        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User|null $user
     * @return $this
     */
    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string|null $imageFilename
     * @return Post
     */
    public function setImage(?string $imageFilename): self
    {
        $this->image = $imageFilename;
        return $this;
    }

    /**
     * @return bool
     */
    public function getIsModerated(): bool
    {
        return $this->is_moderated;
    }

    /**
     * @param bool $is_moderated
     * @return Post
     */
    public function setIsModerated(bool $is_moderated): self
    {
        $this->is_moderated = $is_moderated;
        return $this;
    }


    //*****************************************
    //
    //    Functions for work with comments
    //
    //*****************************************

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }



    //**************************************
    //
    //       The data of the class
    //
    //**************************************

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=false)
     * @Assert\Length(min=3, max=30)
     */
    private $username;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $email;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $homepage;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Post")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @var string|null
     * @Assert\NotBlank(message="plz upload an image")
     * @Assert\Image()
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;


    /**
     * @var bool
     * @ORM\Column(name="is_moderated", type="boolean", nullable=false)
     */
    private $is_moderated;

    /**
     * @var Comment[]
     *
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post")
     */
    private $comments;  // a boolean flag which indicates whether the post has been moderated
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use App\Repository\PostRepository;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

use Symfony\Component\Security\Core\Security;
use Symfony\Component\Translation\TranslatorInterface;
use Twig\Environment;

class PostsController extends Controller
{
    /**
     * PostsController constructor.
     * @param PostRepository $postRepository
     * @param Security $security
     */
    public function __construct(PostRepository $postRepository, Security $security)
    {
        $this->postRepository = $postRepository;
        $this->security = $security;
    }

    /**
     * @Route("/", name="default_address")
     */
    public function index()
    {
        return $this->redirectToRoute("blog_posts");
    }


    public function posts(Request $request)
    {
        $postRepository = $this->getDoctrine()->getRepository(Post::class);
        $page = intval($request->query->get('page', 1));
        $sortBy = $request->query->get('display_order');
        $resultPerPage = 25;
        $numPages = 0;

        if ($page === null)
        {
            $request->query->set('page', 1);
            $page = 1;
        }

        if ($sortBy === null)
        {
            $request->query->set('display_order', 'new');
            $sortBy = 'new';
        }



        $posts = $postRepository->findAllPaginated($numPages, $page, $resultPerPage);

        if ($sortBy === 'old')
        {
            $order = "ASC";
            $posts = $this->sortPostSetBy($posts, "created_at", $order);
        }
        else if ($sortBy === 'new')
        {
            $order = "DESC";
            $posts = $this->sortPostSetBy($posts, "created_at", $order);
        }
        else
        {
            $posts = $this->sortPostSetBy($posts, $sortBy);
        }

        return $this->render('posts/index.html.twig', [
            'posts' => $posts,
            'numPages' => $numPages,
            'curPage' => $page
        ]);
    }

    public function sortPostSetBy($postSetForSort, $sortBy, $order = "ASC")
    {
        if ($sortBy === "created_at")
        {
            if ($order === "DESC")
            {
                usort($postSetForSort, function($post1, $post2)
                {
                    if ($post1->getCreatedAt() == $post2->getCreatedAt()) return 0;
                    return ($post1->getCreatedAt() > $post2->getCreatedAt()) ? -1 : 1;
                });
            }
            else if ($order === "ASC")
            {
                usort($postSetForSort, function($post1, $post2)
                {
                    if ($post1->getCreatedAt() == $post2->getCreatedAt()) return 0;
                    return ($post1->getCreatedAt() < $post2->getCreatedAt()) ? -1 : 1;
                });
            }
        }
        else if ($sortBy === "username")
        {
            usort($postSetForSort, function($post1, $post2)
            {
                if ($post1->getUsername() == $post2->getUsername()) return 0;
                return ($post1->getUsername() < $post2->getUsername()) ? -1 : 1;
            });
        }
        else if ($sortBy === "email")
        {
            usort($postSetForSort, function($post1, $post2)
            {
                if ($post1->getEmail() == $post2->getEmail()) return 0;
                return ($post1->getEmail() < $post2->getEmail()) ? -1 : 1;
            });
        }

        return $postSetForSort;
    }


    /**
     *
     * @param Request $request
     * @param Slugify $slugify
     * @return Response
     */
    public function addPost(Request $request, Slugify $slugify)
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post, ['images_directory' => $this->getParameter('images_directory')]);
        $user = $this->getUser();

        $em = $this->getDoctrine()->getManager();
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid())
        {
            // ReCaptcha handling
            if (!$_POST['g-recaptcha-response'])
                exit('Please, fill the ReCaptcha');

            $url = 'https://www.google.com/recaptcha/api/siteverify';
            $key = '6Lft7qwZAAAAAMTUH3WFuGV18ekY3y3U4_VP3fvB';
            $query = $url.'?secret='.$key.'&response='.$_POST['g-recaptcha-response'].'&remoteip='.$_SERVER['REMOTE_ADDR'];
            $data = json_decode(file_get_contents($query));

            if ($data->success == false)
                exit("Captcha was inputted incorrectly. Please, try again");


            // File upload handling
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();


            // this condition is needed because the 'image' field is not required
            // so the JPG|PNG|GIF file must be processed only when a file is uploaded
            if (is_object($imageFile))
            {
                //$originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL

                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                //$newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();
                $newFilename = md5(uniqid()).'.'.$imageFile->guessExtension();

                // Move the file to the directory where images are stored
                try
                {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                }
                catch (FileException $e)
                {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'image' property to store the JPG|PNG|GIF file name
                // instead of its contents
                $post->setImage($newFilename);
            }
            else
            {
                $post->setImage(null);      // no image is attached to the post
            }


            // set the slug for the URL of this post
            $post->setSlug($slugify->slugify(substr($post->getText(), 0, 20)));     // the first 20 characters of the text will be a slug
            // set the user who created this post
            $post->setUser($user);
            // the post won't be displayed until it is moderated
            $post->setIsModerated(false);

            // save this post in the database
            $em->persist($post);
            $em->flush();


            //return $this->redirectToRoute('blog_posts', ['page' => 1]);
            return $this->render('posts/message_аfter_сreate_post.html.twig');
        }

        return $this->render('posts/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     *
     * @param Request $request
     * @return Response
     */
    public function search(Request $request)
    {
        $query = $request->query->get('q');
        $posts = $this->postRepository->searchByQuery($query);

        return $this->render('posts/query_post.html.twig', [
            'posts' => $posts
        ]);
    }

    /**
     * @param Post $post
     * @param Request $request
     * @param Slugify $slugify
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function edit(Post $post, Request $request, Slugify $slugify)
    {

        $form = $this->createForm(PostType::class, $post, ['images_directory' => $this->getParameter('images_directory')]);
        $em = $this->getDoctrine()->getManager();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            // File upload handling
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();


            // this condition is needed because the 'image' field is not required
            // so the JPG|PNG|GIF file must be processed only when a file is uploaded
            if (is_object($imageFile))      // if we get a class UploadedFile object
            {
                $newFilename = md5(uniqid()).'.'.$imageFile->guessExtension();

                // Move the file to the directory where images are stored
                try
                {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                }
                catch (FileException $e)
                {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'image' property to store the JPG|PNG|GIF file name
                // instead of its contents
                $post->setImage($newFilename);
            }
            // this means that no image has been transferred to the form,
            // use an image that was previously attached to the post
            if ('default_image.png' !== basename($post->getImage()))
            {
                $post->setImage(basename($post->getImage()));
            }
            else        // no image was submitted with the form and no image has been attached to the post before
                $post->setImage(null);

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'posts.main_page.title' | trans }}{% endblock %}

{% block body %}

    <!--------            --------->
    <!--------   SLIDER   --------->
    <!--------            --------->
    {% if curPage == 1 %}
        <div class="container-fluid p-0">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active" ></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="carousel-image">
                            <img src="{{ asset('uploads/images/slider_img_1.png') }}"  alt="computer_dog.png" class="d-block w-100">
                            <span class="overlayed"></span>
                        </div>

                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ 'posts.main_page.slider_greeting_1' | trans }}</h5>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-image">
                            <img src="{{ asset('uploads/images/slider_img_2.jpg') }}"  alt="computer_pirate.png" class="d-block w-100">
                            <span class="overlayed"></span>
                        </div>

                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ 'posts.main_page.slider_greeting_2' | trans }}</h5>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="carousel-image">
                            <img src="{{ asset('uploads/images/slider_img_3.jpg') }}" alt="computer_robber.png" class="d-block w-100">
                            <span class="overlayed"></span>
                        </div>
                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ 'posts.main_page.slider_greeting_3' | trans }}</h5>
                        </div>
                    </div>
                </div>
                <a href="#carouselExampleIndicators" class="carousel-control-prev " role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a href="#carouselExampleIndicators" class="carousel-control-next" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div> <!-- /SLIDER -->
    {% endif %}
    <!--------            --------->
    <!-------  END SLIDER  -------->
    <!--------            --------->
<!--
    <div class="container-fluid">
        <div class="container">
            <div class="row text-center justify-content-center">
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <img src="{{ asset('uploads/images/temp_logo_testing.png')}}" height="200" width="100" alt="logo" class="w-100">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ipsa aliquam velit sequi dlor, necessitatibus ad?</p>
                </div>
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <img src="{{ asset('uploads/imageattributess/temp_logo_testing.png')}}" height="200" width="100" alt="logo" class="w-100">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ipsa aliquam velit sequi dlor, necessitatibus ad?</p>
                </div>
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <img src="{{ asset('uploads/images/temp_logo_testing.png')}}" height="200" width="100" alt="logo" class="w-100">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ipsa aliquam velit sequi dlor, necessitatibus ad?</p>
                </div>
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <img src="{{ asset('uploads/images/temp_logo_testing.png')}}" height="200" width="100" alt="logo" class="w-100">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ipsa aliquam velit sequi dlor, necessitatibus ad?</p>
                </div>
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <img src="{{ asset('uploads/images/temp_logo_testing.png')}}" height="200" width="100" alt="logo" class="w-100">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ipsa aliquam velit sequi dlor, necessitatibus ad?</p>
                </div>
                <div class="col-xs-12 col-sm-4 col-lg-3">
                    <img src="{{ asset('uploads/images/temp_logo_testing.png')}}" height="200" width="100" alt="logo" class="w-100">
                    <h3>Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Ipsa aliquam velit sequi dlor, necessitatibus ad?</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="ml-5 w-25">
            dfgdsfgdfg twert ewt wert wert wert wert wert wert ewrt wert wert wert wert wert wert wert e
        </div>

    </div>
-->




    <!-----  PAGINATION  ----->
    <div class="container class pt-3">
        {% include '/posts/pagination.html.twig' with {'curPage': curPage} %}
    </div>



    <!-----              ----->
    <!-----    POSTS     ----->
    <!-----              ----->
    <div class="container post mx-auto">

        <div class="container-fluid">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="">
                        <!-- button for creating a new post -->
                        {% if app.user %}
                            <div class=" pt-4">
                                <a href="{{ path('new_blog_post') }}">
                                    <button class="btn btn-outline-info">
                                        {{ 'posts.main_page.create_new_post' | trans }}
                                    </button>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <div class="">
                        <div class="btn-group pt-4">
                            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                {{ 'posts.main_page.sort_by.sort_by' | trans }}
                            </button>
                            <!-- button to select the order of display of posts -->
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ path(currentRoute, {'page': currentPage, 'display_order': 'username'})  }}">{{ 'posts.main_page.sort_by.username' | trans }}</a>
                                <a class="dropdown-item" href="{{ path(currentRoute, {'page': currentPage, 'display_order': 'email'})  }}">{{ 'posts.main_page.sort_by.email' | trans }}</a>
                                <a class="dropdown-item" href="{{ path(currentRoute, {'page': currentPage, 'display_order': 'new'})  }}">{{ 'posts.main_page.sort_by.first_new' | trans }}</a>
                                <a class="dropdown-item" href="{{ path(currentRoute, {'page': currentPage, 'display_order': 'old'})  }}">{{ 'posts.main_page.sort_by.first_old' | trans }}</a>
                            </div>  <!-- /.dropdown-menu -->
                        </div>  <!-- /.btn-group -->
                    </div>
                </div>
            </div>
        </div>









        {% for post in posts %}
            {% if post %}
                <br>
                <div class="mx-2 mt-2">
                    <h3><a href="{{ path('blog_show', {'slug': post.slug, 'page': currentPage}) }}">{{ post.text  | slice(0, 30) ~ '...' }}</a></h3>
                </div>
                {% if post.image %}
                    <div class="m-2">
                        <img src="{{ asset('uploads/images/blog_images/' ~ post.image) }}" class="w-75">
                    </div>
                {% endif %}
                <div class="text mx-2">
                    {{ post.text }}
                </div>
                <div class="m-2">
                    <a href="{{ path('blog_show', {'slug': post.slug, 'page': currentPage}) }}">
                        <button class="btn btn-dark">
                            {{ 'posts.main_page.read_more' | trans }}
                        </button>
                    </a>
                </div>
                <div class="dropdown-divider my-2" style="border-color: darkgrey;"></div>
                <span class="mx-2">{{ post.createdAtString }}</span>
                <span class="mx-2">{{ 'posts.main_page.by' | trans }} {{ post.username }}</span>
                <span class="mx-2">{{ post.email }}</span>
                <div class="dropdown-divider my-2" style="border-color: darkgrey;"></div>
                <br>
            {% endif %}
        {% endfor %}
    </div>  <!-- / .container post -->
    <!-----              ----->
    <!-----  END POSTS   ----->
    <!-----              ----->

    <!-----  PAGINATION  ----->
    <div class="container class pt-3">
        {% include '/posts/pagination.html.twig' with {'curPage': curPage} %}
    </div>

{% endblock %}

templates/posts/message_аfter_сreate_post.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'posts.mes_aft_cr_post.title' | trans}}{% endblock %}

{% block body %}
    <div class="container after-create-post mx-auto w-50 mt-5 pt-2">
        {{ 'posts.mes_aft_cr_post.text' | trans}}
        <div class="mt-2">
            <a href="{{ path('blog_posts', {'page': 1}) }}">
                <button class="btn btn-info back_button">
                    {{ 'posts.mes_aft_cr_post.button'  | trans }}
                </button>
            </a>
        </div>
    </div>
{% endblock %}

templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'posts.new_post.title' | trans }}{% endblock %}

{% block body %}
    <div class="container edit-post mx-auto pt-3">
        {{ form_start(form, {'attr': {'class': 'form-group'}}) }}
        <p>{{ 'posts.new_post.username' | trans }}{{ form_widget(form.username, {'attr': {'class': 'text-left  w-100'}}) }}</p>
        <p>{{ 'posts.new_post.email' | trans }}{{ form_widget(form.email, {'attr': {'class': 'text-left  w-100'}}) }}</p>
        <p>{{ 'posts.new_post.homepage' | trans }}{{ form_widget(form.homepage, {'attr': {'class': 'text-left  w-100'}}) }}</p>
        <p>{{ 'posts.new_post.text' | trans }}{{ form_widget(form.text, { 'attr': {
                'class': 'text-left  w-100',
                'rows' : '10',
                'cols' : '10' }}) }}</p>
        <p>{{ 'posts.new_post.image' | trans }}{{ form_widget(form.image) }}</p>
        <div class="g-recaptcha" data-sitekey="6Lft7qwZAAAAAEEe3JtEoGhlKDp6c8mcqinPq-PR"></div>
        <button class="btn btn-dark mt-2" name="enter" type="submit">{{ 'posts.new_post.button' | trans }}</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post.text  | slice(0, 20)}}{% endblock %}

{% block body %}
    <div class="container post_show my-3 mx-auto px-5">
        <div class="py-4">
            {{ post.text }}
        </div>
        {% if post.image %}
            <div class="m-auto">
                <img src="{{ asset('uploads/images/blog_images/' ~ post.image) }}" class="w-100">
            </div>
        {% endif %}
        <div class="mt-2 mb-4">
            <span class="mr-2">{{ post.createdAtString }}</span>
            <span class="mr-2">{{ 'posts.main_page.by' | trans }} {{ post.username }}</span>
            <span class="mr-2">{{ post.email }}</span>
        </div>

        <!--         -->
        <!-- BUTTONS -->
        <!--         -->
        <div class="mb-3">
            {% set referPage = app.request.server.get('HTTP_REFERER') %}
            {% if currentPage != null %}  <!-- variable CurrentPage is the number of the current page with a list of posts -->
                <a href="{{ path('blog_posts', {'page': currentPage}) }}">
                    <button class="btn btn-dark back_button mb-2">
                        {{ 'posts.show_single_post.back' | trans }}
                    </button>
                </a>
            {% else %}
                <a href="{{ referPage }}">
                    <button class="btn btn-dark back_button mb-2">
                        {{ 'posts.show_single_post.back' | trans }}
                    </button>
                </a>
            {% endif %}
        </div>
        {% if app.user %}
            {% if postIsByCurrentUser %}
                <div class="my-2">
                    <a href="{{ path('blog_post_edit', {'slug': post.slug, 'page': currentPage}) }}">
                        <button class="btn btn-outline-success mr-2  pull-right">
                            {{ 'posts.show_single_post.edit' | trans }}
                        </button>
                    </a>
                    <a href="{{ path('blog_post_delete', {'slug': post.slug, 'page': currentPage}) }}">
                        <button class="btn btn-outline-danger  pull-right">
                            {{ 'posts.show_single_post.delete' | trans }}
                        </button>
                    </a>
                </div>
            {% endif %}
        {% endif %}
        <!--             -->
        <!-- END;BUTTONS -->
        <!--             -->

        <div class="pt-5">
            <h3>Comments</h3>
            <div class="dropdown-divider my-2" style="border-color: darkgrey;"></div>
            {% for comment in post.comments %}
                {% if comment.comment != null %}
                    <p>
                        <img src="{{ asset('uploads/images/user_icon.png') }}" width="20" height="20" class="rounded-circle">
                        {{ comment.user.username }}
                        {{ comment.createdAt.format('d-m-y') }} at
                        {{ comment.createdAt.format('H:i') }}
                        <p class="pb-4">
                            {{ comment.comment }}
                        </p>
                    </p>
                {% endif %}
            {% endfor %}

        </div>

        {% if form != null %}
            <div class="pb-3">
                {{ form_start(form) }}
                {{ form_widget(form.comment, {'attr': {'placeholder': 'write the comment'}}) }}
                <br/>
                <button type="submit" class="btn btn-primary">Send</button>
                {{ form_end(form) }}
            </div>
        {% endif %}


    </div>
{% endblock %}